### ISSUE TITLE
Can't find package in Sublime Text 3

### ISSUE THREAD

**Issue by lucascosta** [aroscoe/Hex-to-RGBA#1]
That's it, I can't find the package in Sublime Text 3 package control.

**Comment by aroscoe** [comment]
I've updated to support ST3 and I'm waiting for the package control team to added back to the list. Stay tuned.

**Comment by aroscoe** [comment]
We've combined our efforts with a few different CSS color packages. To continue getting this same functionality, install CSS Color Converter.

**Comment by lucascosta** [comment]
Thanks
