### ISSUE TITLE
Plugin doesn't appear in package control installer

### ISSUE THREAD

**Issue by juanmiguel431** [aroscoe/Hex-to-RGBA#2]
Hello,

I tried to install this plugin but it doesn't appear into package control installer of sublime-text 3. I had to install manually.

**Comment by aroscoe** [comment]
Yeah, its not there because we all decided to only bring one color converter plugin to ST3. As you've done it works if you do it manually. If you want one already in the package manager then you should use: https://packagecontrol.io/packages/CSS%20Color%20Converter 

Thanks for checking it out!
